# Size optimizations
LTO_ENABLE = yes
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes
MUSIC_ENABLE = no
RGBLIGHT_ENABLE = false
CONSOLE_ENABLE = no

# Features
MAGIC_ENABLE = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
OLED_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
WPM_ENABLE = yes
SPLIT_WPM_ENABLE = yes
VIA_ENABLE = yes
